transcode_profile.settings:
  type: config_object
  label: 'Transcode Profile settings'
  mapping:
    transcode_profile:
      type: mapping
      mapping:
        profile_name:
          type: text
          label: 'Profile Name'
        enable_transcoding:
          type: boolean
          label: 'Enable transcoding'