<?php

/**
 * Implements hook_theme().
 */
function movie_db_trailers_theme($existing, $type, $theme, $path) {
  return [
    'trailers_page' => [
      'template'  => 'trailers-page',
      'variables' => [
        'trailers' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function movie_db_trailers_preprocess_node__page(&$variables) {
  $variables['#attached']['library'][] = 'movie_db_trailers/movie_db_trailers';
}
