credentials.credentials.*:
  type: config_entity
  label: 'Credentials config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'Endpoint URL'
    key:
      type: string
      label: 'API key'
    secret:
      type: string
      label: 'API secret'